package entity;
// Generated Jun 27, 2017 12:32:05 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BojeEkrana generated by hbm2java
 */
@Entity
@Table(name="boje_ekrana"
    ,catalog="mobile_shop"
)
public class BojeEkrana  implements java.io.Serializable {


     private Integer bojeId;
     private String vrednost;
     private Set<Model> models = new HashSet<Model>(0);

    public BojeEkrana() {
    }

	
    public BojeEkrana(String vrednost) {
        this.vrednost = vrednost;
    }
    public BojeEkrana(String vrednost, Set<Model> models) {
       this.vrednost = vrednost;
       this.models = models;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="boje_id", unique=true, nullable=false)
    public Integer getBojeId() {
        return this.bojeId;
    }
    
    public void setBojeId(Integer bojeId) {
        this.bojeId = bojeId;
    }

    
    @Column(name="vrednost", nullable=false, length=80)
    public String getVrednost() {
        return this.vrednost;
    }
    
    public void setVrednost(String vrednost) {
        this.vrednost = vrednost;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bojeEkrana")
    public Set<Model> getModels() {
        return this.models;
    }
    
    public void setModels(Set<Model> models) {
        this.models = models;
    }




}


