package entity;
// Generated Jun 27, 2017 12:32:05 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Eksternamemorija generated by hbm2java
 */
@Entity
@Table(name="eksternamemorija"
    ,catalog="mobile_shop"
)
public class Eksternamemorija  implements java.io.Serializable {


     private Integer eksternamemorijaId;
     private String mogucnost;
     private Set<Model> models = new HashSet<Model>(0);

    public Eksternamemorija() {
    }

	
    public Eksternamemorija(String mogucnost) {
        this.mogucnost = mogucnost;
    }
    public Eksternamemorija(String mogucnost, Set<Model> models) {
       this.mogucnost = mogucnost;
       this.models = models;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="eksternamemorija_id", unique=true, nullable=false)
    public Integer getEksternamemorijaId() {
        return this.eksternamemorijaId;
    }
    
    public void setEksternamemorijaId(Integer eksternamemorijaId) {
        this.eksternamemorijaId = eksternamemorijaId;
    }

    
    @Column(name="mogucnost", nullable=false, length=45)
    public String getMogucnost() {
        return this.mogucnost;
    }
    
    public void setMogucnost(String mogucnost) {
        this.mogucnost = mogucnost;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="eksternamemorija")
    public Set<Model> getModels() {
        return this.models;
    }
    
    public void setModels(Set<Model> models) {
        this.models = models;
    }




}


