package entity;
// Generated Jun 27, 2017 12:32:05 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Kamera generated by hbm2java
 */
@Entity
@Table(name="kamera"
    ,catalog="mobile_shop"
)
public class Kamera  implements java.io.Serializable {


     private Integer kameraId;
     private BigDecimal kvalitetKamere;
     private String opis;
     private Set<Model> models = new HashSet<Model>(0);

    public Kamera() {
    }

	
    public Kamera(BigDecimal kvalitetKamere, String opis) {
        this.kvalitetKamere = kvalitetKamere;
        this.opis = opis;
    }
    public Kamera(BigDecimal kvalitetKamere, String opis, Set<Model> models) {
       this.kvalitetKamere = kvalitetKamere;
       this.opis = opis;
       this.models = models;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="kamera_id", unique=true, nullable=false)
    public Integer getKameraId() {
        return this.kameraId;
    }
    
    public void setKameraId(Integer kameraId) {
        this.kameraId = kameraId;
    }

    
    @Column(name="kvalitetKamere", nullable=false, precision=6, scale=1)
    public BigDecimal getKvalitetKamere() {
        return this.kvalitetKamere;
    }
    
    public void setKvalitetKamere(BigDecimal kvalitetKamere) {
        this.kvalitetKamere = kvalitetKamere;
    }

    
    @Column(name="opis", nullable=false, length=45)
    public String getOpis() {
        return this.opis;
    }
    
    public void setOpis(String opis) {
        this.opis = opis;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="kamera")
    public Set<Model> getModels() {
        return this.models;
    }
    
    public void setModels(Set<Model> models) {
        this.models = models;
    }




}


