package entity;
// Generated Jun 27, 2017 12:32:05 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Korisnik generated by hbm2java
 */
@Entity
@Table(name="korisnik"
    ,catalog="mobile_shop"
)
public class Korisnik  implements java.io.Serializable {


     private Integer korisnikId;
     private Prava prava;
     private String ime;
     private String prezime;
     private String username;
     private String password;
     private String email;
     private String adresa;
     private String grad;
     private String telefon;
     private String postanskiBroj;
     private Set<Poruzbina> poruzbinas = new HashSet<Poruzbina>(0);

    public Korisnik() {
    }

    public Korisnik(String ime,String prezime,String korIme,String lozinka,String telBroj,String adresa,String grad,String pb,String eMail, Prava pravo) 
    {
        this.ime = ime;
        this.prezime = prezime;
        this.username = korIme;
        this.password = lozinka;
        this.email = eMail;
        this.adresa = adresa;
        this.grad = grad;
        this.telefon = telBroj;
        this.postanskiBroj = pb;
        this.prava = pravo;
   }
	
    public Korisnik(Prava prava, String ime, String prezime, String username, String password, String email, String adresa, String grad, String telefon, String postanskiBroj) {
        this.prava = prava;
        this.ime = ime;
        this.prezime = prezime;
        this.username = username;
        this.password = password;
        this.email = email;
        this.adresa = adresa;
        this.grad = grad;
        this.telefon = telefon;
        this.postanskiBroj = postanskiBroj;
    }
    public Korisnik(Prava prava, String ime, String prezime, String username, String password, String email, String adresa, String grad, String telefon, String postanskiBroj, Set<Poruzbina> poruzbinas) {
       this.prava = prava;
       this.ime = ime;
       this.prezime = prezime;
       this.username = username;
       this.password = password;
       this.email = email;
       this.adresa = adresa;
       this.grad = grad;
       this.telefon = telefon;
       this.postanskiBroj = postanskiBroj;
       this.poruzbinas = poruzbinas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="korisnik_id", unique=true, nullable=false)
    public Integer getKorisnikId() {
        return this.korisnikId;
    }
    
    public void setKorisnikId(Integer korisnikId) {
        this.korisnikId = korisnikId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pravo_id", nullable=false)
    public Prava getPrava() {
        return this.prava;
    }
    
    public void setPrava(Prava prava) {
        this.prava = prava;
    }

    
    @Column(name="ime", nullable=false, length=45)
    public String getIme() {
        return this.ime;
    }
    
    public void setIme(String ime) {
        this.ime = ime;
    }

    
    @Column(name="prezime", nullable=false, length=45)
    public String getPrezime() {
        return this.prezime;
    }
    
    public void setPrezime(String prezime) {
        this.prezime = prezime;
    }

    
    @Column(name="username", nullable=false, length=45)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", nullable=false, length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="email", nullable=false, length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="adresa", nullable=false, length=100)
    public String getAdresa() {
        return this.adresa;
    }
    
    public void setAdresa(String adresa) {
        this.adresa = adresa;
    }

    
    @Column(name="grad", nullable=false, length=45)
    public String getGrad() {
        return this.grad;
    }
    
    public void setGrad(String grad) {
        this.grad = grad;
    }

    
    @Column(name="telefon", nullable=false, length=45)
    public String getTelefon() {
        return this.telefon;
    }
    
    public void setTelefon(String telefon) {
        this.telefon = telefon;
    }

    
    @Column(name="postanski_broj", nullable=false, length=45)
    public String getPostanskiBroj() {
        return this.postanskiBroj;
    }
    
    public void setPostanskiBroj(String postanskiBroj) {
        this.postanskiBroj = postanskiBroj;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="korisnik")
    public Set<Poruzbina> getPoruzbinas() {
        return this.poruzbinas;
    }
    
    public void setPoruzbinas(Set<Poruzbina> poruzbinas) {
        this.poruzbinas = poruzbinas;
    }




}


