package entity;
// Generated Jun 27, 2017 12:32:05 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Model generated by hbm2java
 */
@Entity
@Table(name="model"
    ,catalog="mobile_shop"
)
public class Model  implements java.io.Serializable, Comparable<Model>  {


     private Integer modelId;
     private Baterija baterija;
     private BojeEkrana bojeEkrana;
     private Dualsim dualsim;
     private Ekran ekran;
     private Eksternamemorija eksternamemorija;
     private InternaMemorija internaMemorija;
     private Kamera kamera;
     private Mreze mreze;
     private Operativnisistem operativnisistem;
     private Proizvodjac proizvodjac;
     private Rammemorija rammemorija;
     private RezolucijaEkrana rezolucijaEkrana;
     private RezolucijaKamere rezolucijaKamere;
     private Status status;
     private Tastatura tastatura;
     private VelicinaEkrana velicinaEkrana;
     private VerzijaOs verzijaOs;
     private String nazivModela;
     private String dimenzijeTelefona;
     private int tezinaTelefona;
     private String referencaSlike;
     private int cena;
     private Set<Stavka> stavkas = new HashSet<Stavka>(0);

    public Model() {
    }

	
    public Model(Baterija baterija, BojeEkrana bojeEkrana, Dualsim dualsim, Ekran ekran, Eksternamemorija eksternamemorija, InternaMemorija internaMemorija, Kamera kamera, Mreze mreze, Operativnisistem operativnisistem, Proizvodjac proizvodjac, Rammemorija rammemorija, RezolucijaEkrana rezolucijaEkrana, RezolucijaKamere rezolucijaKamere, Status status, Tastatura tastatura, VelicinaEkrana velicinaEkrana, VerzijaOs verzijaOs, String nazivModela, String dimenzijeTelefona, int tezinaTelefona, String referencaSlike, int cena) {
        this.baterija = baterija;
        this.bojeEkrana = bojeEkrana;
        this.dualsim = dualsim;
        this.ekran = ekran;
        this.eksternamemorija = eksternamemorija;
        this.internaMemorija = internaMemorija;
        this.kamera = kamera;
        this.mreze = mreze;
        this.operativnisistem = operativnisistem;
        this.proizvodjac = proizvodjac;
        this.rammemorija = rammemorija;
        this.rezolucijaEkrana = rezolucijaEkrana;
        this.rezolucijaKamere = rezolucijaKamere;
        this.status = status;
        this.tastatura = tastatura;
        this.velicinaEkrana = velicinaEkrana;
        this.verzijaOs = verzijaOs;
        this.nazivModela = nazivModela;
        this.dimenzijeTelefona = dimenzijeTelefona;
        this.tezinaTelefona = tezinaTelefona;
        this.referencaSlike = referencaSlike;
        this.cena = cena;
    }
    public Model(Baterija baterija, BojeEkrana bojeEkrana, Dualsim dualsim, Ekran ekran, Eksternamemorija eksternamemorija, InternaMemorija internaMemorija, Kamera kamera, Mreze mreze, Operativnisistem operativnisistem, Proizvodjac proizvodjac, Rammemorija rammemorija, RezolucijaEkrana rezolucijaEkrana, RezolucijaKamere rezolucijaKamere, Status status, Tastatura tastatura, VelicinaEkrana velicinaEkrana, VerzijaOs verzijaOs, String nazivModela, String dimenzijeTelefona, int tezinaTelefona, String referencaSlike, int cena, Set<Stavka> stavkas) {
       this.baterija = baterija;
       this.bojeEkrana = bojeEkrana;
       this.dualsim = dualsim;
       this.ekran = ekran;
       this.eksternamemorija = eksternamemorija;
       this.internaMemorija = internaMemorija;
       this.kamera = kamera;
       this.mreze = mreze;
       this.operativnisistem = operativnisistem;
       this.proizvodjac = proizvodjac;
       this.rammemorija = rammemorija;
       this.rezolucijaEkrana = rezolucijaEkrana;
       this.rezolucijaKamere = rezolucijaKamere;
       this.status = status;
       this.tastatura = tastatura;
       this.velicinaEkrana = velicinaEkrana;
       this.verzijaOs = verzijaOs;
       this.nazivModela = nazivModela;
       this.dimenzijeTelefona = dimenzijeTelefona;
       this.tezinaTelefona = tezinaTelefona;
       this.referencaSlike = referencaSlike;
       this.cena = cena;
       this.stavkas = stavkas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="model_id", unique=true, nullable=false)
    public Integer getModelId() {
        return this.modelId;
    }
    
    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="baterija_id", nullable=false)
    public Baterija getBaterija() {
        return this.baterija;
    }
    
    public void setBaterija(Baterija baterija) {
        this.baterija = baterija;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="brojboja_id", nullable=false)
    public BojeEkrana getBojeEkrana() {
        return this.bojeEkrana;
    }
    
    public void setBojeEkrana(BojeEkrana bojeEkrana) {
        this.bojeEkrana = bojeEkrana;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="dualsim_id", nullable=false)
    public Dualsim getDualsim() {
        return this.dualsim;
    }
    
    public void setDualsim(Dualsim dualsim) {
        this.dualsim = dualsim;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ekran_id", nullable=false)
    public Ekran getEkran() {
        return this.ekran;
    }
    
    public void setEkran(Ekran ekran) {
        this.ekran = ekran;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="eksternamemorija_id", nullable=false)
    public Eksternamemorija getEksternamemorija() {
        return this.eksternamemorija;
    }
    
    public void setEksternamemorija(Eksternamemorija eksternamemorija) {
        this.eksternamemorija = eksternamemorija;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="interna_memorija_id", nullable=false)
    public InternaMemorija getInternaMemorija() {
        return this.internaMemorija;
    }
    
    public void setInternaMemorija(InternaMemorija internaMemorija) {
        this.internaMemorija = internaMemorija;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="kamera_id", nullable=false)
    public Kamera getKamera() {
        return this.kamera;
    }
    
    public void setKamera(Kamera kamera) {
        this.kamera = kamera;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mreze_id", nullable=false)
    public Mreze getMreze() {
        return this.mreze;
    }
    
    public void setMreze(Mreze mreze) {
        this.mreze = mreze;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="operativniSistem_id", nullable=false)
    public Operativnisistem getOperativnisistem() {
        return this.operativnisistem;
    }
    
    public void setOperativnisistem(Operativnisistem operativnisistem) {
        this.operativnisistem = operativnisistem;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="proizvodjac_id", nullable=false)
    public Proizvodjac getProizvodjac() {
        return this.proizvodjac;
    }
    
    public void setProizvodjac(Proizvodjac proizvodjac) {
        this.proizvodjac = proizvodjac;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RAMmemorija_id", nullable=false)
    public Rammemorija getRammemorija() {
        return this.rammemorija;
    }
    
    public void setRammemorija(Rammemorija rammemorija) {
        this.rammemorija = rammemorija;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="rezolucija_ekrana_id", nullable=false)
    public RezolucijaEkrana getRezolucijaEkrana() {
        return this.rezolucijaEkrana;
    }
    
    public void setRezolucijaEkrana(RezolucijaEkrana rezolucijaEkrana) {
        this.rezolucijaEkrana = rezolucijaEkrana;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="rezolucija_kamere_id", nullable=false)
    public RezolucijaKamere getRezolucijaKamere() {
        return this.rezolucijaKamere;
    }
    
    public void setRezolucijaKamere(RezolucijaKamere rezolucijaKamere) {
        this.rezolucijaKamere = rezolucijaKamere;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="status_id", nullable=false)
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tastatura_id", nullable=false)
    public Tastatura getTastatura() {
        return this.tastatura;
    }
    
    public void setTastatura(Tastatura tastatura) {
        this.tastatura = tastatura;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="velicina_ekrana_id", nullable=false)
    public VelicinaEkrana getVelicinaEkrana() {
        return this.velicinaEkrana;
    }
    
    public void setVelicinaEkrana(VelicinaEkrana velicinaEkrana) {
        this.velicinaEkrana = velicinaEkrana;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="verzija_id", nullable=false)
    public VerzijaOs getVerzijaOs() {
        return this.verzijaOs;
    }
    
    public void setVerzijaOs(VerzijaOs verzijaOs) {
        this.verzijaOs = verzijaOs;
    }

    
    @Column(name="nazivModela", nullable=false, length=80)
    public String getNazivModela() {
        return this.nazivModela;
    }
    
    public void setNazivModela(String nazivModela) {
        this.nazivModela = nazivModela;
    }

    
    @Column(name="dimenzije_telefona", nullable=false, length=45)
    public String getDimenzijeTelefona() {
        return this.dimenzijeTelefona;
    }
    
    public void setDimenzijeTelefona(String dimenzijeTelefona) {
        this.dimenzijeTelefona = dimenzijeTelefona;
    }

    
    @Column(name="tezina_telefona", nullable=false)
    public int getTezinaTelefona() {
        return this.tezinaTelefona;
    }
    
    public void setTezinaTelefona(int tezinaTelefona) {
        this.tezinaTelefona = tezinaTelefona;
    }

    
    @Column(name="referenca_slike", nullable=false, length=100)
    public String getReferencaSlike() {
        return this.referencaSlike;
    }
    
    public void setReferencaSlike(String referencaSlike) {
        this.referencaSlike = referencaSlike;
    }

    
    @Column(name="cena", nullable=false)
    public int getCena() {
        return this.cena;
    }
    
    public void setCena(int cena) {
        this.cena = cena;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="model")
    public Set<Stavka> getStavkas() {
        return this.stavkas;
    }
    
    public void setStavkas(Set<Stavka> stavkas) {
        this.stavkas = stavkas;
    }

    @Override
    public int compareTo(Model o) {
        return proizvodjac.getNazivBrenda().compareTo(o.proizvodjac.getNazivBrenda());
    }




}


