package entity;
// Generated Jun 27, 2017 12:32:05 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mreze generated by hbm2java
 */
@Entity
@Table(name="mreze"
    ,catalog="mobile_shop"
)
public class Mreze  implements java.io.Serializable {


     private Integer mrezaId;
     private String mreze;
     private Set<Model> models = new HashSet<Model>(0);

    public Mreze() {
    }

	
    public Mreze(String mreze) {
        this.mreze = mreze;
    }
    public Mreze(String mreze, Set<Model> models) {
       this.mreze = mreze;
       this.models = models;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="mreza_id", unique=true, nullable=false)
    public Integer getMrezaId() {
        return this.mrezaId;
    }
    
    public void setMrezaId(Integer mrezaId) {
        this.mrezaId = mrezaId;
    }

    
    @Column(name="mreze", nullable=false, length=100)
    public String getMreze() {
        return this.mreze;
    }
    
    public void setMreze(String mreze) {
        this.mreze = mreze;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mreze")
    public Set<Model> getModels() {
        return this.models;
    }
    
    public void setModels(Set<Model> models) {
        this.models = models;
    }




}


