package entity;
// Generated Jun 27, 2017 12:32:05 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Operativnisistem generated by hbm2java
 */
@Entity
@Table(name="operativnisistem"
    ,catalog="mobile_shop"
)
public class Operativnisistem  implements java.io.Serializable {


     private Integer osId;
     private String vrstaOperativnogSistema;
     private Set<Model> models = new HashSet<Model>(0);

    public Operativnisistem() {
    }

	
    public Operativnisistem(String vrstaOperativnogSistema) {
        this.vrstaOperativnogSistema = vrstaOperativnogSistema;
    }
    public Operativnisistem(String vrstaOperativnogSistema, Set<Model> models) {
       this.vrstaOperativnogSistema = vrstaOperativnogSistema;
       this.models = models;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="os_id", unique=true, nullable=false)
    public Integer getOsId() {
        return this.osId;
    }
    
    public void setOsId(Integer osId) {
        this.osId = osId;
    }

    
    @Column(name="vrsta_Operativnog_Sistema", nullable=false, length=45)
    public String getVrstaOperativnogSistema() {
        return this.vrstaOperativnogSistema;
    }
    
    public void setVrstaOperativnogSistema(String vrstaOperativnogSistema) {
        this.vrstaOperativnogSistema = vrstaOperativnogSistema;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="operativnisistem")
    public Set<Model> getModels() {
        return this.models;
    }
    
    public void setModels(Set<Model> models) {
        this.models = models;
    }




}


