package entity;
// Generated Jun 27, 2017 12:32:05 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Poruzbina generated by hbm2java
 */
@Entity
@Table(name="poruzbina"
    ,catalog="mobile_shop"
)
public class Poruzbina  implements java.io.Serializable {


     private Integer porudzbinaId;
     private Korisnik korisnik;
     private String statusPorudzbine;
     private int iznos;
     private String opisPorudzbine;
     private Set<Stavka> stavkas = new HashSet<Stavka>(0);

    public Poruzbina() {
    }
    
    	
    public Poruzbina(Korisnik korisnik, String statusPorudzbine, int iznos, String opisPorudzbine) {
        this.korisnik = korisnik;
        this.statusPorudzbine = statusPorudzbine;
        this.iznos = iznos;
        this.opisPorudzbine = opisPorudzbine;
    }
    public Poruzbina(Korisnik korisnik, String statusPorudzbine, int iznos, String opisPorudzbine, Set<Stavka> stavkas) {
       this.korisnik = korisnik;
       this.statusPorudzbine = statusPorudzbine;
       this.iznos = iznos;
       this.opisPorudzbine = opisPorudzbine;
       this.stavkas = stavkas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="porudzbina_id", unique=true, nullable=false)
    public Integer getPorudzbinaId() {
        return this.porudzbinaId;
    }
    
    public void setPorudzbinaId(Integer porudzbinaId) {
        this.porudzbinaId = porudzbinaId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="korisnik_id", nullable=false)
    public Korisnik getKorisnik() {
        return this.korisnik;
    }
    
    public void setKorisnik(Korisnik korisnik) {
        this.korisnik = korisnik;
    }

    
    @Column(name="statusPorudzbine", nullable=false, length=45)
    public String getStatusPorudzbine() {
        return this.statusPorudzbine;
    }
    
    public void setStatusPorudzbine(String statusPorudzbine) {
        this.statusPorudzbine = statusPorudzbine;
    }

    
    @Column(name="iznos", nullable=false)
    public int getIznos() {
        return this.iznos;
    }
    
    public void setIznos(int iznos) {
        this.iznos = iznos;
    }

    
    @Column(name="opisPorudzbine", nullable=false, length=45)
    public String getOpisPorudzbine() {
        return this.opisPorudzbine;
    }
    
    public void setOpisPorudzbine(String opisPorudzbine) {
        this.opisPorudzbine = opisPorudzbine;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="poruzbina")
    public Set<Stavka> getStavkas() {
        return this.stavkas;
    }
    
    public void setStavkas(Set<Stavka> stavkas) {
        this.stavkas = stavkas;
    }




}


