package entity;
// Generated Jun 27, 2017 12:32:05 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Prava generated by hbm2java
 */
@Entity
@Table(name="prava"
    ,catalog="mobile_shop"
)
public class Prava  implements java.io.Serializable {


     private Integer pravaId;
     private String pravo;
     private Set<Korisnik> korisniks = new HashSet<Korisnik>(0);

    public Prava() {
    }

	
    public Prava(String pravo) {
        this.pravo = pravo;
    }
    public Prava(String pravo, Set<Korisnik> korisniks) {
       this.pravo = pravo;
       this.korisniks = korisniks;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="prava_id", unique=true, nullable=false)
    public Integer getPravaId() {
        return this.pravaId;
    }
    
    public void setPravaId(Integer pravaId) {
        this.pravaId = pravaId;
    }

    
    @Column(name="pravo", nullable=false, length=45)
    public String getPravo() {
        return this.pravo;
    }
    
    public void setPravo(String pravo) {
        this.pravo = pravo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="prava")
    public Set<Korisnik> getKorisniks() {
        return this.korisniks;
    }
    
    public void setKorisniks(Set<Korisnik> korisniks) {
        this.korisniks = korisniks;
    }




}


