package entity;
// Generated Jun 27, 2017 12:32:05 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RezolucijaEkrana generated by hbm2java
 */
@Entity
@Table(name="rezolucija_ekrana"
    ,catalog="mobile_shop"
)
public class RezolucijaEkrana  implements java.io.Serializable {


     private Integer rezolucijaEkranaId;
     private String rezolucija;
     private Set<Model> models = new HashSet<Model>(0);

    public RezolucijaEkrana() {
    }

	
    public RezolucijaEkrana(String rezolucija) {
        this.rezolucija = rezolucija;
    }
    public RezolucijaEkrana(String rezolucija, Set<Model> models) {
       this.rezolucija = rezolucija;
       this.models = models;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="rezolucija_ekrana_id", unique=true, nullable=false)
    public Integer getRezolucijaEkranaId() {
        return this.rezolucijaEkranaId;
    }
    
    public void setRezolucijaEkranaId(Integer rezolucijaEkranaId) {
        this.rezolucijaEkranaId = rezolucijaEkranaId;
    }

    
    @Column(name="rezolucija", nullable=false, length=45)
    public String getRezolucija() {
        return this.rezolucija;
    }
    
    public void setRezolucija(String rezolucija) {
        this.rezolucija = rezolucija;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="rezolucijaEkrana")
    public Set<Model> getModels() {
        return this.models;
    }
    
    public void setModels(Set<Model> models) {
        this.models = models;
    }




}


