package entity;
// Generated Jun 27, 2017 12:32:05 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RezolucijaKamere generated by hbm2java
 */
@Entity
@Table(name="rezolucija_kamere"
    ,catalog="mobile_shop"
)
public class RezolucijaKamere  implements java.io.Serializable {


     private Integer kameraRezId;
     private String rezolucijaKamere;
     private String opis;
     private Set<Model> models = new HashSet<Model>(0);

    public RezolucijaKamere() {
    }

	
    public RezolucijaKamere(String rezolucijaKamere, String opis) {
        this.rezolucijaKamere = rezolucijaKamere;
        this.opis = opis;
    }
    public RezolucijaKamere(String rezolucijaKamere, String opis, Set<Model> models) {
       this.rezolucijaKamere = rezolucijaKamere;
       this.opis = opis;
       this.models = models;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="kameraRez_id", unique=true, nullable=false)
    public Integer getKameraRezId() {
        return this.kameraRezId;
    }
    
    public void setKameraRezId(Integer kameraRezId) {
        this.kameraRezId = kameraRezId;
    }

    
    @Column(name="rezolucija_kamere", nullable=false, length=80)
    public String getRezolucijaKamere() {
        return this.rezolucijaKamere;
    }
    
    public void setRezolucijaKamere(String rezolucijaKamere) {
        this.rezolucijaKamere = rezolucijaKamere;
    }

    
    @Column(name="opis", nullable=false, length=45)
    public String getOpis() {
        return this.opis;
    }
    
    public void setOpis(String opis) {
        this.opis = opis;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="rezolucijaKamere")
    public Set<Model> getModels() {
        return this.models;
    }
    
    public void setModels(Set<Model> models) {
        this.models = models;
    }




}


