package entity;
// Generated Jun 27, 2017 12:32:05 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Stavka generated by hbm2java
 */
@Entity
@Table(name="stavka"
    ,catalog="mobile_shop"
)
public class Stavka  implements java.io.Serializable {


     private Integer stavkaId;
     private Model model;
     private Poruzbina poruzbina;
     private int kolicina;

    public Stavka() {
    }

    public Stavka(Model model, Poruzbina poruzbina, int kolicina) {
       this.model = model;
       this.poruzbina = poruzbina;
       this.kolicina = kolicina;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="stavka_id", unique=true, nullable=false)
    public Integer getStavkaId() {
        return this.stavkaId;
    }
    
    public void setStavkaId(Integer stavkaId) {
        this.stavkaId = stavkaId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="model_id", nullable=false)
    public Model getModel() {
        return this.model;
    }
    
    public void setModel(Model model) {
        this.model = model;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="porudzbina_id", nullable=false)
    public Poruzbina getPoruzbina() {
        return this.poruzbina;
    }
    
    public void setPoruzbina(Poruzbina poruzbina) {
        this.poruzbina = poruzbina;
    }

    
    @Column(name="kolicina", nullable=false)
    public int getKolicina() {
        return this.kolicina;
    }
    
    public void setKolicina(int kolicina) {
        this.kolicina = kolicina;
    }




}


