package entity;
// Generated Jun 27, 2017 12:32:05 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tastatura generated by hbm2java
 */
@Entity
@Table(name="tastatura"
    ,catalog="mobile_shop"
)
public class Tastatura  implements java.io.Serializable {


     private Integer tastaturaId;
     private String vrstaTastature;
     private Set<Model> models = new HashSet<Model>(0);

    public Tastatura() {
    }

	
    public Tastatura(String vrstaTastature) {
        this.vrstaTastature = vrstaTastature;
    }
    public Tastatura(String vrstaTastature, Set<Model> models) {
       this.vrstaTastature = vrstaTastature;
       this.models = models;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="tastatura_id", unique=true, nullable=false)
    public Integer getTastaturaId() {
        return this.tastaturaId;
    }
    
    public void setTastaturaId(Integer tastaturaId) {
        this.tastaturaId = tastaturaId;
    }

    
    @Column(name="vrstaTastature", nullable=false, length=45)
    public String getVrstaTastature() {
        return this.vrstaTastature;
    }
    
    public void setVrstaTastature(String vrstaTastature) {
        this.vrstaTastature = vrstaTastature;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tastatura")
    public Set<Model> getModels() {
        return this.models;
    }
    
    public void setModels(Set<Model> models) {
        this.models = models;
    }




}


