package entity;
// Generated Jun 27, 2017 12:32:05 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VerzijaOs generated by hbm2java
 */
@Entity
@Table(name="verzija_os"
    ,catalog="mobile_shop"
)
public class VerzijaOs  implements java.io.Serializable {


     private Integer verzijaId;
     private String verzija;
     private Set<Model> models = new HashSet<Model>(0);

    public VerzijaOs() {
    }

	
    public VerzijaOs(String verzija) {
        this.verzija = verzija;
    }
    public VerzijaOs(String verzija, Set<Model> models) {
       this.verzija = verzija;
       this.models = models;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="verzija_id", unique=true, nullable=false)
    public Integer getVerzijaId() {
        return this.verzijaId;
    }
    
    public void setVerzijaId(Integer verzijaId) {
        this.verzijaId = verzijaId;
    }

    
    @Column(name="verzija", nullable=false, length=45)
    public String getVerzija() {
        return this.verzija;
    }
    
    public void setVerzija(String verzija) {
        this.verzija = verzija;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="verzijaOs")
    public Set<Model> getModels() {
        return this.models;
    }
    
    public void setModels(Set<Model> models) {
        this.models = models;
    }




}


